spring:
  application:
    name: license-service
  config:
    import: optional:configserver:http://config-server:8071
  cloud:
    config:
      headers:
        X-Config-Token: ${VAULT_TOKEN}
services:
  organization:
    url: http://organization-service
